name: Ruby Specs

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6.x', '2.7.x', '3.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Test with Rake
      run: |
        sudo apt-get install libxml2-utils
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
    - name: Check with Rubocop
      run: |
        bundle exec rubocop
